#!/bin/bash
FILE=bin/kernel
make clean
make
if test -f "./$FILE"; then
    valgrind --tool=memcheck --leak-check=full --show-possibly-lost=yes --show-reachable=yes --num-callers=20  --track-origins=yes ./$FILE $@
fi